name: first workflow

on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: welcome message
          run: echo "Hello World"
        
        - name: checkout
          uses: actions/checkout@v4.2.2
          
        - name: List files 
          run: ls

        - name: readfile
          run: cat README.md
